FROM php:8.3-fpm-alpine

RUN apk add --no-cache \
    git unzip zip curl bash \
    icu-dev oniguruma-dev libzip-dev $PHPIZE_DEPS

RUN docker-php-ext-install pdo pdo_mysql opcache intl zip

RUN pecl install apcu && docker-php-ext-enable apcu

WORKDIR /var/www/html

COPY backend /var/www/html

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN composer install --no-dev --optimize-autoloader --classmap-authoritative