services:
  frontend:
    image: tryanever/green_market-frontend:latest
    container_name: frontend
    expose:
      - "5173"
    restart: unless-stopped

  php:
    image: tryanever/green_market-backend:latest
    container_name: php
    expose:
      - "9000"
    restart: unless-stopped

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db

volumes:
  db_data:
